# Generated by Django 6.0.7 on 2026-09-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='LUNCH', max_length=32)),
                ('consumed_at', models.DateTimeField()),
                ('total_calories', models.IntegerField(default=0)),
                ('protein_g', models.IntegerField(default=0)),
                ('carbs_g', models.IntegerField(default=0)),
                ('fat_g', models.IntegerField(default=0)),
                ('fiber_g', models.IntegerField(default=0)),
                ('food_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
